<script lang="ts">
	import { Upload, Play, Download, Info, Dna } from 'lucide-svelte';
	
	let sequenceInput = '';
	let selectedFile: File | null = null;
	let isAnalyzing = false;
	let analysisResult: any = null;
	
	function handleFileSelect(event: Event) {
		const target = event.target as HTMLInputElement;
		if (target.files && target.files[0]) {
			selectedFile = target.files[0];
		}
	}
	
	async function startAnalysis() {
		if (!sequenceInput.trim() && !selectedFile) {
			alert('请输入蛋白质序列或上传FASTA文件');
			return;
		}
		
		isAnalyzing = true;
		
		// 模拟分析过程
		await new Promise(resolve => setTimeout(resolve, 3000));
		
		// 模拟结果
		analysisResult = {
			confidence: 0.85,
			structure: 'predicted_structure.pdb',
			residues: sequenceInput.length || 150,
			domains: ['Domain 1: 1-50', 'Domain 2: 51-100', 'Domain 3: 101-150']
		};
		
		isAnalyzing = false;
	}
	
	function downloadResult() {
		// 模拟下载
		const blob = new Blob(['# Predicted protein structure\n# Generated by OpenFold'], { type: 'text/plain' });
		const url = URL.createObjectURL(blob);
		const a = document.createElement('a');
		a.href = url;
		a.download = 'predicted_structure.pdb';
		a.click();
		URL.revokeObjectURL(url);
	}
</script>

<svelte:head>
	<title>Alphafold - 蛋白质结构预测</title>
</svelte:head>

<div class="max-w-6xl mx-auto">
	<!-- 页面头部 -->
	<div class="mb-8">
		<div class="flex items-center mb-4">
			<div class="p-3 bg-blue-500 rounded-lg mr-4">
				<Dna class="w-8 h-8 text-white" />
			</div>
			<div>
				<h1 class="text-3xl font-bold text-gray-900 dark:text-white">AlphaFold</h1>
				<p class="text-gray-600 dark:text-gray-400">基于深度学习的蛋白质结构预测</p>
			</div>
		</div>
		
		<div class="bg-blue-50 dark:bg-blue-900 border border-blue-200 dark:border-blue-700 rounded-lg p-4">
			<div class="flex items-start">
				<Info class="w-5 h-5 text-blue-600 dark:text-blue-400 mt-0.5 mr-3 flex-shrink-0" />
				<div class="text-sm text-blue-800 dark:text-blue-200">
					<p class="font-medium mb-1">关于AlphaFold</p>
					<p>AlphaFold是一个开源的蛋白质结构预测工具，基于AlphaFold2的架构，能够从氨基酸序列预测蛋白质的三维结构。</p>
				</div>
			</div>
		</div>
	</div>

	<div class="grid grid-cols-1 lg:grid-cols-2 gap-8">
		<!-- 输入区域 -->
		<div class="space-y-6">
			<div class="card">
				<h2 class="text-xl font-semibold text-gray-900 dark:text-white mb-4">
					输入蛋白质序列
				</h2>
				
				<!-- 序列输入 -->
				<div class="mb-4">
					<label for="sequence" class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
						氨基酸序列 (FASTA格式)
					</label>
					<textarea
						id="sequence"
						bind:value={sequenceInput}
						rows="8"
						class="input resize-none"
						placeholder="请输入蛋白质序列，例如：
>Protein_1
MKTVRQERLKSIVRILERSKEPVSGAQLAEELSVSRQVIVQDIAYLRSLGYNIVATPRGYVLAGG
SKTFQGVNFGSVGFAIRYIYQADSTPVSGTAPFGGEIIDERGGYADRVTLRLNVENPKLWSAEI"
					></textarea>
				</div>
				
				<!-- 文件上传 -->
				<div class="mb-6">
					<label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
						或上传FASTA文件
					</label>
					<div class="border-2 border-dashed border-gray-300 dark:border-gray-600 rounded-lg p-6 text-center hover:border-primary-500 transition-colors">
						<Upload class="w-8 h-8 text-gray-400 mx-auto mb-2" />
						<p class="text-sm text-gray-600 dark:text-gray-400 mb-2">
							点击选择文件或拖拽文件到此处
						</p>
						<input
							type="file"
							accept=".fasta,.fa,.txt"
							on:change={handleFileSelect}
							class="hidden"
							id="file-upload"
						/>
						<label for="file-upload" class="btn btn-secondary cursor-pointer">
							选择文件
						</label>
						{#if selectedFile}
							<p class="text-sm text-green-600 dark:text-green-400 mt-2">
								已选择: {selectedFile.name}
							</p>
						{/if}
					</div>
				</div>
				
				<!-- 分析按钮 -->
				<button
					on:click={startAnalysis}
					disabled={isAnalyzing || (!sequenceInput.trim() && !selectedFile)}
					class="btn btn-primary w-full flex items-center justify-center"
				>
					{#if isAnalyzing}
						<div class="animate-spin rounded-full h-5 w-5 border-b-2 border-white mr-2"></div>
						分析中...
					{:else}
						<Play class="w-5 h-5 mr-2" />
						开始结构预测
					{/if}
				</button>
			</div>
			
			<!-- 参数设置 -->
			<div class="card">
				<h3 class="text-lg font-semibold text-gray-900 dark:text-white mb-4">
					预测参数
				</h3>
				<div class="space-y-4">
					<div>
						<label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
							模型版本
						</label>
						<select class="input">
							<option>AlphaFold v1.0</option>
							<option>AlphaFold v2.0 (推荐)</option>
						</select>
					</div>
					<div>
						<label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
							置信度阈值
						</label>
						<input type="range" min="0.5" max="1.0" step="0.05" value="0.7" class="w-full" />
						<div class="flex justify-between text-xs text-gray-500 mt-1">
							<span>0.5</span>
							<span>1.0</span>
						</div>
					</div>
				</div>
			</div>
		</div>

		<!-- 结果区域 -->
		<div class="space-y-6">
			{#if analysisResult}
				<div class="card">
					<h2 class="text-xl font-semibold text-gray-900 dark:text-white mb-4">
						预测结果
					</h2>
					
					<!-- 结果统计 -->
					<div class="grid grid-cols-2 gap-4 mb-6">
						<div class="bg-gray-50 dark:bg-gray-700 rounded-lg p-4 text-center">
							<div class="text-2xl font-bold text-primary-600 dark:text-primary-400">
								{(analysisResult.confidence * 100).toFixed(1)}%
							</div>
							<div class="text-sm text-gray-600 dark:text-gray-400">平均置信度</div>
						</div>
						<div class="bg-gray-50 dark:bg-gray-700 rounded-lg p-4 text-center">
							<div class="text-2xl font-bold text-primary-600 dark:text-primary-400">
								{analysisResult.residues}
							</div>
							<div class="text-sm text-gray-600 dark:text-gray-400">氨基酸残基数</div>
						</div>
					</div>
					
					<!-- 结构域信息 -->
					<div class="mb-6">
						<h3 class="text-lg font-medium text-gray-900 dark:text-white mb-3">
							预测的结构域
						</h3>
						<div class="space-y-2">
							{#each analysisResult.domains as domain}
								<div class="bg-gray-50 dark:bg-gray-700 rounded-lg p-3">
									<span class="text-sm text-gray-700 dark:text-gray-300">{domain}</span>
								</div>
							{/each}
						</div>
					</div>
					
					<!-- 3D结构预览 -->
					<div class="mb-6">
						<h3 class="text-lg font-medium text-gray-900 dark:text-white mb-3">
							3D结构预览
						</h3>
						<div class="bg-gray-100 dark:bg-gray-700 rounded-lg h-64 flex items-center justify-center">
							<div class="text-center text-gray-500 dark:text-gray-400">
								<Dna class="w-12 h-12 mx-auto mb-2" />
								<p>3D结构查看器</p>
								<p class="text-sm">(需要集成Mol*或其他分子查看器)</p>
							</div>
						</div>
					</div>
					
					<!-- 下载按钮 -->
					<div class="flex space-x-3">
						<button
							on:click={downloadResult}
							class="btn btn-primary flex items-center"
						>
							<Download class="w-4 h-4 mr-2" />
							下载PDB文件
						</button>
						<button class="btn btn-secondary">
							查看详细报告
						</button>
					</div>
				</div>
			{:else}
				<div class="card">
					<div class="text-center py-12">
						<Dna class="w-16 h-16 text-gray-400 mx-auto mb-4" />
						<h3 class="text-lg font-medium text-gray-900 dark:text-white mb-2">
							等待分析
						</h3>
						<p class="text-gray-600 dark:text-gray-400">
							请输入蛋白质序列并开始预测
						</p>
					</div>
				</div>
			{/if}
		</div>
	</div>
</div> 